### Read all users(req to protected route)
GET http://localhost:3000/user-api/users


### Read a user by id
GET http://localhost:3000/user-api/users/69b242b7fc69a7311eaf09d2

### Create new user
POST http://localhost:3000/user-api/users
Content-Type: application/json

{
    "username":"abcdf",
    "password":"ram",
    "email":"abcdf@mail.com",
    "age":20
}


### Update a User
PUT http://localhost:3000/user-api/users/69aa8b34b58f738b45eed7cd
Content-Type: application/json

{
    "username":"abcdf",
    "password":"ram",
    "email":"abcdef@mail.com",
    "age":20
}


### user login
POST http://localhost:3000/user-api/auth
Content-Type: application/json

{
    "email":"abcdf@mail.com",
    "password":"ram"
}


### Delete a user by ID
DELETE http://localhost:3000/user-api/users/69aa8a4393875279636a2d70


### add product to user cart 
PUT http://localhost:3000/user-api/cart/product-id/69b256950a145491777fa51a








###
GET http://localhost:3000/product-api/products

###
POST http://localhost:3000/product-api/product
Content-Type: application/json

{
    "productId":1,
    "productName":"keyboard",
    "brand":"sam",
    "price":10000
}

###
PUT http://localhost:3000/product-api/products
Content-Type: application/json

{
    "productId":1,
    "name":"laptop",
    "brand":"hp",
    "price":260
}

###
DELETE http://localhost:3000/product-api/products/1


